# Generated by Django 3.2 on 2022-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alter_ego',
            field=models.CharField(blank=True, choices=[('AN', 'Pick Your Alter Ego'), ('AV', 'The Avengers'), ('BA', 'Batman'), ('CA', 'Captain America'), ('FL', 'The Flash'), ('HU', 'The Hulk'), ('IR', 'Iron Man'), ('SP', 'Spiderman'), ('TH', 'Thor'), ('WW', 'Wonder Woman')], default='AN', max_length=2, null=True),
        ),
    ]
