# Generated by Django 3.2 on 2022-11-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
