# Generated by Django 3.2 on 2022-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special_gift',
            field=models.CharField(blank=True, choices=[('HU', 'Hulk'), ('BA', 'Batman'), ('WW', 'Wonder Woman'), ('TH', 'Thor'), ('SP', 'Spider Man'), ('AV', 'The Avengers'), ('FL', 'The Flash'), ('CA', 'Captain America'), ('IR', 'Iron Man')], default='BA', max_length=2, null=True),
        ),
    ]
