# Generated by Django 3.2 on 2022-11-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_special_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special_gift',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_gift_active',
        ),
    ]
