# Generated by Django 3.2 on 2022-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20221125_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_dispatch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
