# Generated by Django 3.2 on 2022-11-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20221127_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='use_shipping_address',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
