# Generated by Django 3.2 on 2022-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_use_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_street_address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_street_address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_town_or_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='use_shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
