# Generated by Django 3.2 on 2022-11-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20221127_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_dispatch_date',
            field=models.DateTimeField(blank=True, default='estimated_dispatch_calc', null=True),
        ),
    ]
