# Generated by Django 3.2 on 2022-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_estimated_dispatch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_dispatch_date',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_days_to_dispatch',
            field=models.CharField(blank=True, default='2', max_length=2, null=True),
        ),
    ]
