# Generated by Django 3.2 on 2022-11-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=254)),
                ('name', models.SlugField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('author', models.CharField(blank=True, max_length=350, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=350, null=True)),
                ('asin', models.CharField(blank=True, max_length=254, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('print_length', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=254, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=30, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hero', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
