# Generated by Django 3.2 on 2022-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221128_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
